
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
      # we are adding this to publish 100% logs to zipkin

app:
  client:
    url: http://localhost:4200

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: chronicle-register
          uri: lb://chronicle-register
          predicates:
            - Path=/register/**
        - id: chronicle-backend
          uri: lb://chronicle-backend
          predicates:
            - Path=/api/**
            - Path=/admin/**
            - Path=/login/**
            - Path=/signup/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: 'http://localhost:4200'
#            allowedHeaders:
#              - Content-Type
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS